export const buildingClassToBuildableClass: Record<string, string | null> = {
  // cspell:disable
  Desc_Wall_Concrete_8x1_C: "Build_Wall_Concrete_8x1_C",
  Desc_Wall_Concrete_8x4_C: "Build_Wall_Concrete_8x4_C",
  Desc_Wall_Concrete_8x4_ConveyorHole_01_C:
    "Build_Wall_Concrete_8x4_ConveyorHole_01_C",
  Desc_Wall_Concrete_8x4_ConveyorHole_02_C:
    "Build_Wall_Concrete_8x4_ConveyorHole_02_C",
  Desc_Wall_Concrete_8x4_ConveyorHole_03_C:
    "Build_Wall_Concrete_8x4_ConveyorHole_03_C",
  Desc_Wall_Concrete_8x4_Corner_01_C: "Build_Wall_Concrete_8x4_Corner_01_C",
  Desc_Wall_Concrete_8x4_Corner_2_C: "Build_Wall_Concrete_8x4_Corner_2_C",
  Desc_Wall_Concrete_8x4_Window_01_C: "Build_Wall_Concrete_8x4_Window_01_C",
  Desc_Wall_Concrete_8x4_Window_02_C: "Build_Wall_Concrete_8x4_Window_02_C",
  Desc_Wall_Concrete_8x4_Window_03_C: "Build_Wall_Concrete_8x4_Window_03_C",
  Desc_Wall_Concrete_8x4_Window_04_C: "Build_Wall_Concrete_8x4_Window_04_C",
  Desc_Wall_Concrete_8x8_Corner_01_C: "Build_Wall_Concrete_8x8_Corner_01_C",
  Desc_Wall_Concrete_8x8_Corner_2_C: "Build_Wall_Concrete_8x8_Corner_2_C",
  Desc_Wall_Concrete_Angular_8x4_C: "Build_Wall_Concrete_Angular_8x4_C",
  Desc_Wall_Concrete_Angular_8x8_C: "Build_Wall_Concrete_Angular_8x8_C",
  Desc_Wall_Concrete_CDoor_8x4_C: "Build_Wall_Concrete_CDoor_8x4_C",
  Desc_Wall_Concrete_8x1_FlipTris_C: "Build_Wall_Concrete_FlipTris_8x1_C",
  Desc_Wall_Concrete_8x2_FlipTris_C: "Build_Wall_Concrete_FlipTris_8x2_C",
  Desc_Wall_Concrete_8x4_FlipTris_C: "Build_Wall_Concrete_FlipTris_8x4_C",
  Desc_Wall_Concrete_8x8_FlipTris_C: "Build_Wall_Concrete_FlipTris_8x8_C",
  Desc_Wall_Concrete_Gate_8x4_C: "Build_Wall_Concrete_Gate_8x4_C",
  Desc_Wall_Concrete_SDoor_8x4_C: "Build_Wall_Concrete_SDoor_8x4_C",
  Desc_Wall_Concrete_8x1_Tris_C: "Build_Wall_Concrete_Tris_8x1_C",
  Desc_Wall_Concrete_8x2_Tris_C: "Build_Wall_Concrete_Tris_8x2_C",
  Desc_Wall_Concrete_8x4_Tris_C: "Build_Wall_Concrete_Tris_8x4_C",
  Desc_Wall_Concrete_8x8_Tris_C: "Build_Wall_Concrete_Tris_8x8_C",
  Desc_Wall_8x4_01_C: "Build_Wall_8x4_01_C",
  Desc_Wall_Conveyor_8x4_01_C: "Build_Wall_Conveyor_8x4_01_C",
  Desc_Wall_Conveyor_8x4_02_C: "Build_Wall_Conveyor_8x4_02_C",
  Desc_Wall_Conveyor_8x4_03_C: "Build_Wall_Conveyor_8x4_03_C",
  Desc_Wall_Door_8x4_01_C: "Build_Wall_Door_8x4_01_C",
  Desc_Wall_Door_8x4_03_C: "Build_Wall_Door_8x4_03_C",
  Desc_Wall_Gate_8x4_01_C: "Build_Wall_Gate_8x4_01_C",
  Desc_Wall_Orange_8x1_C: "Build_Wall_Orange_8x1_C",
  Desc_Wall_Orange_8x4_Corner_01_C: "Build_Wall_Orange_8x4_Corner_01_C",
  Desc_Wall_Orange_8x4_Corner_02_C: "Build_Wall_Orange_8x4_Corner_02_C",
  Desc_Wall_Orange_8x8_Corner_01_C: "Build_Wall_Orange_8x8_Corner_01_C",
  Desc_Wall_Orange_8x8_Corner_02_C: "Build_Wall_Orange_8x8_Corner_02_C",
  Desc_Wall_Orange_Angular_8x4_C: "Build_Wall_Orange_Angular_8x4_C",
  Desc_Wall_Orange_Angular_8x8_C: "Build_Wall_Orange_Angular_8x8_C",
  Desc_Wall_Orange_8x1_FlipTris_C: "Build_Wall_Orange_FlipTris_8x1_C",
  Desc_Wall_Orange_8x2_FlipTris_C: "Build_Wall_Orange_FlipTris_8x2_C",
  Desc_Wall_Orange_8x4_FlipTris_C: "Build_Wall_Orange_FlipTris_8x4_C",
  Desc_Wall_Orange_8x8_FlipTris_C: "Build_Wall_Orange_FlipTris_8x8_C",
  Desc_Wall_Orange_8x1_Tris_C: "Build_Wall_Orange_Tris_8x1_C",
  Desc_Wall_Orange_8x2_Tris_C: "Build_Wall_Orange_Tris_8x2_C",
  Desc_Wall_Orange_8x4_Tris_C: "Build_Wall_Orange_Tris_8x4_C",
  Desc_Wall_Orange_8x8_Tris_C: "Build_Wall_Orange_Tris_8x8_C",
  Desc_Wall_Window_8x4_01_C: "Build_Wall_Window_8x4_01_C",
  Desc_Wall_Window_8x4_02_C: "Build_Wall_Window_8x4_02_C",
  Desc_Wall_Window_8x4_03_C: "Build_Wall_Window_8x4_03_C",
  Desc_Wall_Window_8x4_04_C: "Build_Wall_Window_8x4_04_C",
  Desc_SteelWall_8x4_Gate_01_C: "Build_SteelWall_8x4_Gate_01_C",
  Desc_SteelWall_8x4_Window_01_C: "Build_SteelWall_8x4_Window_01_C",
  Desc_SteelWall_8x4_Window_02_C: "Build_SteelWall_8x4_Window_02_C",
  Desc_SteelWall_8x4_Window_03_C: "Build_SteelWall_8x4_Window_03_C",
  Desc_SteelWall_8x4_Window_04_C: "Build_SteelWall_8x4_Window_04_C",
  Desc_Wall_Steel_8x4_Corner_01_C: "Build_Wall_Steel_8x4_Corner_01_C",
  Desc_Wall_Steel_8x4_Corner_2_C: "Build_Wall_Steel_8x4_Corner_2_C",
  Desc_Wall_Steel_8x8_Corner_01_C: "Build_Wall_Steel_8x8_Corner_01_C",
  Desc_Wall_Steel_8x8_Corner_2_C: "Build_Wall_Steel_8x8_Corner_2_C",
  Desc_SteelWall_8x1_C: "Build_SteelWall_8x1_C",
  Desc_SteelWall_FlipTris_8x1_C: "Build_SteelWall_FlipTris_8x1_C",
  Desc_SteelWall_FlipTris_8x2_C: "Build_SteelWall_FlipTris_8x2_C",
  Desc_SteelWall_FlipTris_8x4_C: "Build_SteelWall_FlipTris_8x4_C",
  Desc_SteelWall_FlipTris_8x8_C: "Build_SteelWall_FlipTris_8x8_C",
  Desc_SteelWall_Tris_8x1_C: "Build_SteelWall_Tris_8x1_C",
  Desc_SteelWall_Tris_8x2_C: "Build_SteelWall_Tris_8x2_C",
  Desc_SteelWall_Tris_8x4_C: "Build_SteelWall_Tris_8x4_C",
  Desc_SteelWall_Tris_8x8_C: "Build_SteelWall_Tris_8x8_C",
  Desc_Wall_8x4_02_C: "Build_Wall_8x4_02_C",
  Desc_Wall_Conveyor_8x4_01_Steel_C: "Build_Wall_Conveyor_8x4_01_Steel_C",
  Desc_Wall_Conveyor_8x4_02_Steel_C: "Build_Wall_Conveyor_8x4_02_Steel_C",
  Desc_Wall_Conveyor_8x4_03_Steel_C: "Build_Wall_Conveyor_8x4_03_Steel_C",
  Desc_Wall_Door_8x4_01_Steel_C: "Build_Wall_Door_8x4_01_Steel_C",
  Desc_Wall_Door_8x4_03_Steel_C: "Build_Wall_Door_8x4_03_Steel_C",
  Desc_WallSet_Steel_Angular_8x4_C: "Build_WallSet_Steel_Angular_8x4_C",
  Desc_WallSet_Steel_Angular_8x8_C: "Build_WallSet_Steel_Angular_8x8_C",
  Desc_Beam_C: "Build_Beam_C",
  Desc_Beam_Painted_C: "Build_Beam_Painted_C",
  Desc_ConveyorCeilingAttachment_C: "Build_ConveyorCeilingAttachment_C",
  Desc_ConveyorPoleWall_C: "Build_ConveyorPoleWall_C",
  Desc_ConveyorBeltMk1_C: "Build_ConveyorBeltMk1_C",
  Desc_PowerLine_C: "Build_PowerLine_C",
  Desc_PowerPoleMk1_C: "Build_PowerPoleMk1_C",
  Desc_PowerPoleWall_C: "Build_PowerPoleWall_C",
  Desc_TradingPost_C: "Build_TradingPost_C",
  Desc_WorkBench_C: "Build_WorkBench_C",
  Desc_Fence_01_C: "Build_Fence_01_C",
  Desc_PillarTop_C: "Build_PillarTop_C",
  Desc_JumpPad_C: "Build_JumpPad_C",
  Desc_JumpPadTilted_C: "Build_JumpPadTilted_C",
  Desc_WalkwayCross_C: "Build_WalkwayCross_C",
  Desc_WalkwayRamp_C: "Build_WalkwayRamp_C",
  Desc_WalkwayStraight_C: "Build_WalkwayStraight_C",
  Desc_WalkwayT_C: "Build_WalkwayT_C",
  Desc_WalkwayTurn_C: "Build_WalkwayTrun_C",
  Desc_SteelWall_8x4_C: "Build_SteelWall_8x4_C",
  Desc_Wall_Conveyor_8x4_04_C: "Build_Wall_Conveyor_8x4_04_C",
  Desc_Wall_Conveyor_8x4_04_Steel_C: "Build_Wall_Conveyor_8x4_04_Steel_C",
  Desc_Wall_Window_8x4_03_Steel_C: null,
  Desc_GeneratorCoal_C: "Build_GeneratorCoal_C",
  Desc_PipelineSupportWall_C: "Build_PipelineSupportWall_C",
  Desc_Pipeline_C: "Build_Pipeline_C",
  Desc_PipelineJunction_Cross_C: "Build_PipelineJunction_Cross_C",
  Desc_PipelinePump_C: "Build_PipelinePump_C",
  Desc_PipeStorageTank_C: "Build_PipeStorageTank_C",
  Desc_WaterPump_C: "Build_WaterPump_C",
  Desc_ResourceSink_C: "Build_ResourceSink_C",
  Desc_ResourceSinkShop_C: "Build_ResourceSinkShop_C",
  Desc_QuantumEncoder_C: "Build_QuantumEncoder_C",
  Desc_Converter_C: "Build_Converter_C",
  Desc_OilPump_C: "Build_OilPump_C",
  Desc_OilRefinery_C: "Build_OilRefinery_C",
  Desc_Valve_C: "Build_Valve_C",
  Desc_FoundryMk1_C: "Build_FoundryMk1_C",
  Desc_Packager_C: "Build_Packager_C",
  Desc_MinerMk2_C: "Build_MinerMk2_C",
  Desc_ManufacturerMk1_C: "Build_ManufacturerMk1_C",
  Desc_AssemblerMk1_C: "Build_AssemblerMk1_C",
  Desc_HadronCollider_C: "Build_HadronCollider_C",
  Desc_Blender_C: "Build_Blender_C",
  Desc_GeneratorNuclear_C: "Build_GeneratorNuclear_C",
  Desc_FrackingExtractor_C: "Build_FrackingExtractor_C",
  Desc_FrackingSmasher_C: "Build_FrackingSmasher_C",
  Desc_DroneStation_C: "Build_DroneStation_C",
  Desc_ConveyorBeltMk5_C: "Build_ConveyorBeltMk5_C",
  Desc_ConveyorLiftMk5_C: "Build_ConveyorLiftMk5_C",
  Desc_MinerMk3_C: "Build_MinerMk3_C",
  Desc_ConveyorBeltMk6_C: "Build_ConveyorBeltMk6_C",
  Desc_ConveyorLiftMk6_C: "Build_ConveyorLiftMk6_C",
  Desc_Portal_C: "Build_Portal_C",
  Desc_PortalSatellite_C: "Build_PortalSatellite_C",
  Desc_BlueprintDesigner_MK3_C: "Build_BlueprintDesigner_Mk3_C",
  Desc_RailroadBlockSignal_C: "Build_RailroadBlockSignal_C",
  Desc_RailroadPathSignal_C: "Build_RailroadPathSignal_C",
  Desc_BlueprintDesigner_MK2_C: "Build_BlueprintDesigner_MK2_C",
  Desc_PipelineMK2_C: "Build_PipelineMK2_C",
  Desc_PipelinePumpMk2_C: "Build_PipelinePumpMk2_C",
  Desc_TrainDockingStation_C: "Build_TrainDockingStation_C",
  Desc_TrainDockingStationLiquid_C: "Build_TrainDockingStationLiquid_C",
  Desc_TrainPlatformEmpty_C: "Build_TrainPlatformEmpty_C",
  Desc_TrainPlatformEmpty_02_C: "Build_TrainPlatformEmpty_02_C",
  Desc_TrainStation_C: "Build_TrainStation_C",
  Desc_RailroadTrack_C: "Build_RailroadTrack_C",
  Desc_ConveyorBeltMk4_C: "Build_ConveyorBeltMk4_C",
  Desc_ConveyorLiftMk4_C: "Build_ConveyorLiftMk4_C",
  Desc_GeneratorFuel_C: "Build_GeneratorFuel_C",
  Desc_IndustrialTank_C: "Build_IndustrialTank_C",
  Desc_ConveyorBeltMk3_C: "Build_ConveyorBeltMk3_C",
  Desc_ConveyorLiftMk3_C: "Build_ConveyorLiftMk3_C",
  Desc_StorageContainerMk2_C: "Build_StorageContainerMk2_C",
  Desc_BlueprintDesigner_C: "Build_BlueprintDesigner_C",
  Desc_PipeHyperStart_C: "Build_PipeHyperStart_C",
  Desc_HyperTubeWallSupport_C: "Build_HyperTubeWallSupport_C",
  Desc_PipeHyper_C: "Build_PipeHyper_C",
  Desc_PowerStorageMk1_C: "Build_PowerStorageMk1_C",
  Desc_PowerTower_C: "Build_PowerTower_C",
  Desc_PowerTowerPlatform_C: "Build_PowerTowerPlatform_C",
  Desc_TruckStation_C: "Build_TruckStation_C",
  Desc_ConveyorBeltMk2_C: "Build_ConveyorBeltMk2_C",
  Desc_ConveyorLiftMk2_C: "Build_ConveyorLiftMk2_C",
  Desc_JumpPadAdjustable_C: "Build_JumpPadAdjustable_C",
  Desc_LandingPad_C: "Build_LandingPad_C",
  Desc_Mam_C: "Build_Mam_C",
  Desc_StoragePlayer_C: "Build_StoragePlayer_C",
  Desc_ConveyorAttachmentMerger_C: "Build_ConveyorAttachmentMerger_C",
  Desc_ConveyorAttachmentSplitter_C: "Build_ConveyorAttachmentSplitter_C",
  Desc_ConveyorLiftMk1_C: "Build_ConveyorLiftMk1_C",
  Desc_QuarterPipeMiddle_Ficsit_4x1_C: "Build_QuarterPipeMiddle_Ficsit_8x1_C",
  Desc_QuarterPipeMiddle_Ficsit_4x2_C: "Build_QuarterPipeMiddle_Ficsit_8x2_C",
  Desc_QuarterPipeMiddle_Ficsit_4x4_C: "Build_QuarterPipeMiddle_Ficsit_8x4_C",
  Desc_QuarterPipeMiddleInCorner_Ficsit_8x1_C:
    "Build_QuarterPipeMiddleInCorner_Ficsit_8x1_C",
  Desc_QuarterPipeMiddleInCorner_Ficsit_8x2_C:
    "Build_QuarterPipeMiddleInCorner_Ficsit_8x2_C",
  Desc_QuarterPipeMiddleInCorner_Ficsit_8x4_C:
    "Build_QuarterPipeMiddleInCorner_Ficsit_8x4_C",
  Desc_QuarterPipeMiddleOutCorner_Ficsit_4x1_C:
    "Build_QuarterPipeMiddleOutCorner_Ficsit_4x1_C",
  Desc_QuarterPipeMiddleOutCorner_Ficsit_4x2_C:
    "Build_QuarterPipeMiddleOutCorner_Ficsit_4x2_C",
  Desc_QuarterPipeMiddleOutCorner_Ficsit_4x4_C:
    "Build_QuarterPipeMiddleOutCorner_Ficsit_4x4_C",
  Desc_Stair_FicsitSet_8x1_01_C: "Build_Stair_FicsitSet_8x1_01_C",
  Desc_Stair_FicsitSet_8x2_01_C: "Build_Stair_FicsitSet_8x2_01_C",
  Desc_Stair_FicsitSet_8x4_01_C: "Build_Stair_FicsitSet_8x4_01_C",
  Desc_Foundation_8x1_01_C: "Build_Foundation_8x1_01_C",
  Desc_Foundation_8x2_01_C: "Build_Foundation_8x2_01_C",
  Desc_Foundation_8x4_01_C: "Build_Foundation_8x4_01_C",
  Desc_QuarterPipe_C: "Build_QuarterPipe_C",
  Desc_QuarterPipe_02_C: "Build_QuarterPipe_02_C",
  Desc_QuarterPipeCorner_01_C: "Build_QuarterPipeCorner_01_C",
  Desc_QuarterPipeCorner_02_C: "Build_QuarterPipeCorner_02_C",
  Desc_QuarterPipeCorner_03_C: "Build_QuarterPipeCorner_03_C",
  Desc_QuarterPipeCorner_04_C: "Build_QuarterPipeCorner_04_C",
  Desc_Ramp_8x1_01_C: "Build_Ramp_8x1_01_C",
  Desc_Ramp_8x2_01_C: "Build_Ramp_8x2_01_C",
  Desc_Ramp_8x4_01_C: "Build_Ramp_8x4_01_C",
  Desc_Ramp_8x4_Inverted_01_C: "Build_Ramp_8x4_Inverted_01_C",
  Desc_Ramp_8x8x8_C: "Build_Ramp_8x8x8_C",
  Desc_Ramp_Diagonal_8x1_01_C: "Build_Ramp_Diagonal_8x1_01_C",
  Desc_Ramp_Diagonal_8x1_02_C: "Build_Ramp_Diagonal_8x1_02_C",
  Desc_Ramp_Diagonal_8x2_01_C: "Build_Ramp_Diagonal_8x2_01_C",
  Desc_Ramp_Diagonal_8x2_02_C: "Build_Ramp_Diagonal_8x2_02_C",
  Desc_Ramp_Diagonal_8x4_01_C: "Build_Ramp_Diagonal_8x4_01_C",
  Desc_Ramp_Diagonal_8x4_02_C: "Build_Ramp_Diagonal_8x4_02_C",
  Desc_RampDouble_C: "Build_RampDouble_C",
  Desc_RampDouble_8x1_C: "Build_RampDouble_8x1_C",
  Desc_RampInverted_8x1_C: "Build_RampInverted_8x1_C",
  Desc_RampInverted_8x1_Corner_01_C: "Build_RampInverted_8x1_Corner_01_C",
  Desc_RampInverted_8x1_Corner_02_C: "Build_RampInverted_8x1_Corner_02_C",
  Desc_RampInverted_8x2_01_C: "Build_RampInverted_8x2_01_C",
  Desc_RampInverted_8x2_Corner_01_C: "Build_RampInverted_8x2_Corner_01_C",
  Desc_RampInverted_8x2_Corner_02_C: "Build_RampInverted_8x2_Corner_02_C",
  Desc_RampInverted_8x4_Corner_01_C: "Build_RampInverted_8x4_Corner_01_C",
  Desc_RampInverted_8x4_Corner_02_C: "Build_RampInverted_8x4_Corner_02_C",
  Desc_LookoutTower_C: "Build_LookoutTower_C",
  Desc_DownQuarterPipe_Concrete_8x4_C: "Build_DownQuarterPipe_Concrete_8x4_C",
  Desc_DownQuarterPipeInCorner_Concrete_8x4_C:
    "Build_DownQuarterPipeInCorner_Concrete_8x4_C",
  Desc_DownQuarterPipeOutCorner_Concrete_8x4_C:
    "Build_DownQuarterPipeOutCorner_Concrete_8x4_C",
  Desc_Foundation_Concrete_8x1_C: "Build_Foundation_Concrete_8x1_C",
  Desc_Foundation_Concrete_8x2_C: "Build_Foundation_Concrete_8x2_C",
  Desc_Foundation_Concrete_8x4_C: "Build_Foundation_Concrete_8x4_C",
  Desc_InvertedRamp_Concrete_8x1_C: "Build_InvertedRamp_Concrete_8x1_C",
  Desc_InvertedRamp_Concrete_8x2_C: "Build_InvertedRamp_Concrete_8x2_C",
  Desc_InvertedRamp_Concrete_8x4_C: "Build_InvertedRamp_Concrete_8x4_C",
  Desc_InvertedRamp_DCorner_Concrete_8x1_C:
    "Build_InvertedRamp_DCorner_Concrete_8x1_C",
  Desc_InvertedRamp_DCorner_Concrete_8x2_C:
    "Build_InvertedRamp_DCorner_Concrete_8x2_C",
  Desc_InvertedRamp_DCorner_Concrete_8x4_C:
    "Build_InvertedRamp_DCorner_Concrete_8x4_C",
  Desc_InvertedRamp_UCorner_Concrete_8x1_C:
    "Build_InvertedRamp_UCorner_Concrete_8x1_C",
  Desc_InvertedRamp_UCorner_Concrete_8x2_C:
    "Build_InvertedRamp_UCorner_Concrete_8x2_C",
  Desc_InvertedRamp_UCorner_Concrete_8x4_C:
    "Build_InvertedRamp_UCorner_Concrete_8x4_C",
  Desc_QuarterPipe_Concrete_8x4_C: "Build_QuarterPipe_Concrete_8x4_C",
  Desc_QuarterPipeInCorner_Concrete_8x4_C:
    "Build_QuarterPipeInCorner_Concrete_8x4_C",
  Desc_QuarterPipeMiddle_Concrete_8x1_C:
    "Build_QuarterPipeMiddle_Concrete_8x1_C",
  Desc_QuarterPipeMiddle_Concrete_8x2_C:
    "Build_QuarterPipeMiddle_Concrete_8x2_C",
  Desc_QuarterPipeMiddle_Concrete_8x4_C:
    "Build_QuarterPipeMiddle_Concrete_8x4_C",
  Desc_QuarterPipeMiddleInCorner_Concrete_8x1_C:
    "Build_QuarterPipeMiddleInCorner_Concrete_8x1_C",
  Desc_QuarterPipeMiddleInCorner_Concrete_8x2_C:
    "Build_QuarterPipeMiddleInCorner_Concrete_8x2_C",
  Desc_QuarterPipeMiddleInCorner_Concrete_8x4_C:
    "Build_QuarterPipeMiddleInCorner_Concrete_8x4_C",
  Desc_QuarterPipeMiddleOutCorner_Concrete_4x1_C:
    "Build_QuarterPipeMiddleOutCorner_Concrete_4x1_C",
  Desc_QuarterPipeMiddleOutCorner_Concrete_4x2_C:
    "Build_QuarterPipeMiddleOutCorner_Concrete_4x2_C",
  Desc_QuarterPipeMiddleOutCorner_Concrete_4x4_C:
    "Build_QuarterPipeMiddleOutCorner_Concrete_4x4_C",
  Desc_QuarterPipeOutCorner_Concrete_8x4_C:
    "Build_QuarterPipeOutCorner_Concrete_8x4_C",
  Desc_Ramp_Concrete_8x1_C: "Build_Ramp_Concrete_8x1_C",
  Desc_Ramp_Concrete_8x2_C: "Build_Ramp_Concrete_8x2_C",
  Desc_Ramp_Concrete_8x4_C: "Build_Ramp_Concrete_8x4_C",
  Desc_Ramp_DownCorner_Concrete_8x1_C: "Build_Ramp_DownCorner_Concrete_8x1_C",
  Desc_Ramp_DownCorner_Concrete_8x2_C: "Build_Ramp_DownCorner_Concrete_8x2_C",
  Desc_Ramp_DownCorner_Concrete_8x4_C: "Build_Ramp_DownCorner_Concrete_8x4_C",
  Desc_Ramp_UpCorner_Concrete_8x1_C: "Build_Ramp_UpCorner_Concrete_8x1_C",
  Desc_Ramp_UpCorner_Concrete_8x2_C: "Build_Ramp_UpCorner_Concrete_8x2_C",
  Desc_Ramp_UpCorner_Concrete_8x4_C: "Build_Ramp_UpCorner_Concrete_8x4_C",
  Desc_RampDouble_Concrete_8x1_C: "Build_RampDouble_Concrete_8x1_C",
  Desc_RampDouble_Concrete_8x2_C: "Build_RampDouble_Concrete_8x2_C",
  Desc_RampDouble_Concrete_8x4_C: "Build_RampDouble_Concrete_8x4_C",
  Desc_Stair_Concrete_8x1_C: "Build_Stair_Concrete_8x1_C",
  Desc_Stair_Concrete_8x2_C: "Build_Stair_Concrete_8x2_C",
  Desc_Stair_Concrete_8x4_C: "Build_Stair_Concrete_8x4_C",
  Desc_DownQuarterPipe_Grip_8x4_C: "Build_DownQuarterPipe_Grip_8x4_C",
  Desc_DownQuarterPipeInCorner_Grip_8x4_C:
    "Build_DownQuarterPipeInCorner_Grip_8x4_C",
  Desc_DownQuarterPipeOutCorner_Grip_8x4_C:
    "Build_DownQuarterPipeOutCorner_Grip_8x4_C",
  Desc_Foundation_Metal_8x1_C: "Build_Foundation_Metal_8x1_C",
  Desc_Foundation_Metal_8x2_C: "Build_Foundation_Metal_8x2_C",
  Desc_Foundation_Metal_8x4_C: "Build_Foundation_Metal_8x4_C",
  Desc_InvertedRamp_DCorner_Metal_8x1_C:
    "Build_InvertedRamp_DCorner_Metal_8x1_C",
  Desc_InvertedRamp_DCorner_Metal_8x2_C:
    "Build_InvertedRamp_DCorner_Metal_8x2_C",
  Desc_InvertedRamp_DCorner_Metal_8x4_C:
    "Build_InvertedRamp_DCorner_Metal_8x4_C",
  Desc_InvertedRamp_Metal_8x1_C: "Build_InvertedRamp_Metal_8x1_C",
  Desc_InvertedRamp_Metal_8x2_C: "Build_InvertedRamp_Metal_8x2_C",
  Desc_InvertedRamp_Metal_8x4_C: "Build_InvertedRamp_Metal_8x4_C",
  Desc_InvertedRamp_UCorner_Metal_8x1_C:
    "Build_InvertedRamp_UCorner_Metal_8x1_C",
  Desc_InvertedRamp_UCorner_Metal_8x2_C:
    "Build_InvertedRamp_UCorner_Metal_8x2_C",
  Desc_InvertedRamp_UCorner_Metal_8x4_C:
    "Build_InvertedRamp_UCorner_Metal_8x4_C",
  Desc_QuarterPipe_Grip_8x4_C: "Build_QuarterPipe_Grip_8x4_C",
  Desc_QuarterPipeInCorner_Grip_8x4_C: "Build_QuarterPipeInCorner_Grip_8x4_C",
  Desc_QuarterPipeMiddle_Grip_8x1_C: "Build_QuarterPipeMiddle_Grip_8x1_C",
  Desc_QuarterPipeMiddle_Grip_8x2_C: "Build_QuarterPipeMiddle_Grip_8x2_C",
  Desc_QuarterPipeMiddle_Grip_8x4_C: "Build_QuarterPipeMiddle_Grip_8x4_C",
  Desc_QuarterPipeMiddleInCorner_Grip_8x1_C:
    "Build_QuarterPipeMiddleInCorner_Grip_8x1_C",
  Desc_QuarterPipeMiddleInCorner_Grip_8x2_C:
    "Build_QuarterPipeMiddleInCorner_Grip_8x2_C",
  Desc_QuarterPipeMiddleInCorner_Grip_8x4_C:
    "Build_QuarterPipeMiddleInCorner_Grip_8x4_C",
  Desc_QuarterPipeMiddleOutCorner_Grip_4x1_C:
    "Build_QuarterPipeMiddleOutCorner_Grip_4x1_C",
  Desc_QuarterPipeMiddleOutCorner_Grip_4x2_C:
    "Build_QuarterPipeMiddleOutCorner_Grip_4x2_C",
  Desc_QuarterPipeMiddleOutCorner_Grip_4x4_C:
    "Build_QuarterPipeMiddleOutCorner_Grip_4x4_C",
  Desc_QuarterPipeOutCorner_Grip_8x4_C: "Build_QuarterPipeOutCorner_Grip_8x4_C",
  Desc_Ramp_DownCorner_Metal_8x1_C: "Build_Ramp_DownCorner_Metal_8x1_C",
  Desc_Ramp_DownCorner_Metal_8x2_C: "Build_Ramp_DownCorner_Metal_8x2_C",
  Desc_Ramp_DownCorner_Metal_8x4_C: "Build_Ramp_DownCorner_Metal_8x4_C",
  Desc_Ramp_Metal_8x1_C: "Build_Ramp_Metal_8x1_C",
  Desc_Ramp_Metal_8x2_C: "Build_Ramp_Metal_8x2_C",
  Desc_Ramp_Metal_8x4_C: "Build_Ramp_Metal_8x4_C",
  Desc_Ramp_UpCorner_Metal_8x1_C: "Build_Ramp_UpCorner_Metal_8x1_C",
  Desc_Ramp_UpCorner_Metal_8x2_C: "Build_Ramp_UpCorner_Metal_8x2_C",
  Desc_Ramp_UpCorner_Metal_8x4_C: "Build_Ramp_UpCorner_Metal_8x4_C",
  Desc_RampDouble_Metal_8x1_C: "Build_RampDouble_Metal_8x1_C",
  Desc_RampDouble_Metal_8x2_C: "Build_RampDouble_Metal_8x2_C",
  Desc_RampDouble_Metal_8x4_C: "Build_RampDouble_Metal_8x4_C",
  Desc_Stair_GripMetal_8x1_C: "Build_Stair_GripMetal_8x1_C",
  Desc_Stair_GripMetal_8x2_C: "Build_Stair_GripMetal_8x2_C",
  Desc_Stair_GripMetal_8x4_C: "Build_Stair_GripMetal_8x4_C",
  Desc_DownQuarterPipe_ConcretePolished_8x4_C:
    "Build_DownQuarterPipe_ConcretePolished_8x4_C",
  Desc_DownQuarterPipeInCorner_ConcretePolished_8x4_C:
    "Build_DownQuarterPipeInCorner_ConcretePolished_8x4_C",
  Desc_DownQuarterPipeOutCorner_ConcretePolished_8x4_C:
    "Build_DownQuarterPipeOutCorner_ConcretePolished_8x4_C",
  Desc_Foundation_ConcretePolished_8x1_C:
    "Build_Foundation_ConcretePolished_8x1_C",
  Foundation_ConcretePolished_8x2_C:
    "Build_Foundation_ConcretePolished_8x2_2_C",
  Foundation_ConcretePolished_8x4_C: "Build_Foundation_ConcretePolished_8x4_C",
  Desc_InvertedRamp_DCorner_Polished_8x1_C:
    "Build_InvertedRamp_DCorner_Polished_8x1_C",
  Desc_InvertedRamp_DCorner_Polished_8x2_C:
    "Build_InvertedRamp_DCorner_Polished_8x2_C",
  Desc_InvertedRamp_DCorner_Polished_8x4_C:
    "Build_InvertedRamp_DCorner_Polished_8x4_C",
  Desc_InvertedRamp_Polished_8x1_C: "Build_InvertedRamp_Polished_8x1_C",
  Desc_InvertedRamp_Polished_8x2_C: "Build_InvertedRamp_Polished_8x2_C",
  Desc_InvertedRamp_Polished_8x4_C: "Build_InvertedRamp_Polished_8x4_C",
  Desc_InvertedRamp_UCorner_Polished_8x1_C:
    "Build_InvertedRamp_UCorner_Polished_8x1_C",
  Desc_InvertedRamp_UCorner_Polished_8x2_C:
    "Build_InvertedRamp_UCorner_Polished_8x2_C",
  Desc_InvertedRamp_UCorner_Polished_8x4_C:
    "Build_InvertedRamp_UCorner_Polished_8x4_C",
  Desc_QuarterPipe_ConcretePolished_8x4_C:
    "Build_QuarterPipe_ConcretePolished_8x4_C",
  Desc_QuarterPipeInCorner_ConcretePolished_8x4_C:
    "Build_QuarterPipeInCorner_ConcretePolished_8x4_C",
  Desc_QuarterPipeMiddle_PolishedConcrete_8x1_C:
    "Build_QuarterPipeMiddle_PolishedConcrete_8x1_C",
  Desc_QuarterPipeMiddle_PolishedConcrete_8x2_C:
    "Build_QuarterPipeMiddle_PolishedConcrete_8x2_C",
  Desc_QuarterPipeMiddle_PolishedConcrete_8x4_C:
    "Build_QuarterPipeMiddle_PolishedConcrete_8x4_C",
  Desc_QuarterPipeMiddleInCorner_PolishedConcrete_8x1_C:
    "Build_QuarterPipeMiddleInCorner_PolishedConcrete_8x1_C",
  Desc_QuarterPipeMiddleInCorner_PolishedConcrete_8x2_C:
    "Build_QuarterPipeMiddleInCorner_PolishedConcrete_8x2_C",
  Desc_QuarterPipeMiddleInCorner_PolishedConcrete_8x4_C:
    "Build_QuarterPipeMiddleInCorner_PolishedConcrete_8x4_C",
  Desc_QuarterPipeMiddleOutCorner_PolishedConcrete_4x1_C:
    "Build_QuarterPipeMiddleOutCorner_PolishedConcrete_4x1_C",
  Desc_QuarterPipeMiddleOutCorner_PolishedConcrete_4x2_C:
    "Build_QuarterPipeMiddleOutCorner_PolishedConcrete_4x2_C",
  Desc_QuarterPipeMiddleOutCorner_PolishedConcrete_4x4_C:
    "Build_QuarterPipeMiddleOutCorner_PolishedConcrete_4x4_C",
  Desc_QuarterPipeOutCorner_ConcretePolished_8x4_C:
    "Build_QuarterPipeOutCorner_ConcretePolished_8x4_C",
  Desc_Ramp_DownCorner_Polished_8x1_C: "Build_Ramp_DownCorner_Polished_8x1_C",
  Desc_Ramp_DownCorner_Polished_8x2_C: "Build_Ramp_DownCorner_Polished_8x2_C",
  Desc_Ramp_DownCorner_Polished_8x4_C: "Build_Ramp_DownCorner_Polished_8x4_C",
  Desc_Ramp_Polished_8x1_C: "Build_Ramp_Polished_8x1_C",
  Desc_Ramp_Polished_8x2_C: "Build_Ramp_Polished_8x2_C",
  Desc_Ramp_Polished_8x4_C: "Build_Ramp_Polished_8x4_C",
  Desc_Ramp_UpCorner_Polished_8x1_C: "Build_Ramp_UpCorner_Polished_8x1_C",
  Desc_Ramp_UpCorner_Polished_8x2_C: "Build_Ramp_UpCorner_Polished_8x2_C",
  Desc_Ramp_UpCorner_Polished_8x4_C: "Build_Ramp_UpCorner_Polished_8x4_C",
  Desc_RampDouble_Polished_8x1_C: "Build_RampDouble_Polished_8x1_C",
  Desc_RampDouble_Polished_8x2_C: "Build_RampDouble_Polished_8x2_C",
  Desc_RampDouble_Polished_8x4_C: "Build_RampDouble_Polished_8x4_C",
  Desc_Stair_PolishedConcrete_8x1_C: "Build_Stair_PolishedConcrete_8x1_C",
  Desc_Stair_PolishedConcrete_8x2_C: "Build_Stair_PolishedConcrete_8x2_C",
  Desc_Stair_PolishedConcrete_8x4_C: "Build_Stair_PolishedConcrete_8x4_C",
  Desc_DownQuarterPipe_Asphalt_8x4_C: "Build_DownQuarterPipe_Asphalt_8x4_C",
  Desc_DownQuarterPipeInCorner_Asphalt_8x4_C:
    "Build_DownQuarterPipeInCorner_Asphalt_8x4_C",
  Desc_DownQuarterPipeOutCorner_Asphalt_8x4_C:
    "Build_DownQuarterPipeOutCorner_Asphalt_8x4_C",
  Desc_Foundation_Asphalt_8x1_C: "Build_Foundation_Asphalt_8x1_C",
  Desc_Foundation_Asphalt_8x2_C: "Build_Foundation_Asphalt_8x2_C",
  Desc_Foundation_Asphalt_8x4_C: "Build_Foundation_Asphalt_8x4_C",
  Desc_InvertedRamp_Asphalt_8x1_C: "Build_InvertedRamp_Asphalt_8x1_C",
  Desc_InvertedRamp_Asphalt_8x2_C: "Build_InvertedRamp_Asphalt_8x2_C",
  Desc_InvertedRamp_Asphalt_8x4_C: "Build_InvertedRamp_Asphalt_8x4_C",
  Desc_InvertedRamp_DCorner_Asphalt_8x1_C:
    "Build_InvertedRamp_DCorner_Asphalt_8x1_C",
  Desc_InvertedRamp_DCorner_Asphalt_8x2_C:
    "Build_InvertedRamp_DCorner_Asphalt_8x2_C",
  Desc_InvertedRamp_DCorner_Asphalt_8x4_C:
    "Build_InvertedRamp_DCorner_Asphalt_8x4_C",
  Desc_InvertedRamp_UCorner_Asphalt_8x1_C:
    "Build_InvertedRamp_UCorner_Asphalt_8x1_C",
  Desc_InvertedRamp_UCorner_Asphalt_8x2_C:
    "Build_InvertedRamp_UCorner_Asphalt_8x2_C",
  Desc_InvertedRamp_UCorner_Asphalt_8x4_C:
    "Build_InvertedRamp_UCorner_Asphalt_8x4_C",
  Desc_QuarterPipe_Asphalt_8x4_C: "Build_QuarterPipe_Asphalt_8x4_C",
  Desc_QuarterPipeInCorner_Asphalt_8x4_C:
    "Build_QuarterPipeInCorner_Asphalt_8x4_C",
  Desc_QuarterPipeMiddle_Asphalt_8x1_C: "Build_QuarterPipeMiddle_Asphalt_8x1_C",
  Desc_QuarterPipeMiddle_Asphalt_8x2_C: "Build_QuarterPipeMiddle_Asphalt_8x2_C",
  Desc_QuarterPipeMiddle_Asphalt_8x4_C: "Build_QuarterPipeMiddle_Asphalt_8x4_C",
  Desc_QuarterPipeMiddleInCorner_Asphalt_8x1_C:
    "Build_QuarterPipeMiddleInCorner_Asphalt_8x1_C",
  Desc_QuarterPipeMiddleInCorner_Asphalt_8x2_C:
    "Build_QuarterPipeMiddleInCorner_Asphalt_8x2_C",
  Desc_QuarterPipeMiddleInCorner_Asphalt_8x4_C:
    "Build_QuarterPipeMiddleInCorner_Asphalt_8x4_C",
  Desc_QuarterPipeMiddleOutCorner_Asphalt_4x1_C:
    "Build_QuarterPipeMiddleOutCorner_Asphalt_4x1_C",
  Desc_QuarterPipeMiddleOutCorner_Asphalt_4x2_C:
    "Build_QuarterPipeMiddleOutCorner_Asphalt_4x2_C",
  Desc_QuarterPipeMiddleOutCorner_Asphalt_4x4_C:
    "Build_QuarterPipeMiddleOutCorner_Asphalt_4x4_C",
  Desc_QuarterPipeOutCorner_Asphalt_8x4_C:
    "Build_QuarterPipeOutCorner_Asphalt_8x4_C",
  Desc_Ramp_Asphalt_8x1_C: "Build_Ramp_Asphalt_8x1_C",
  Desc_Ramp_Asphalt_8x2_C: "Build_Ramp_Asphalt_8x2_C",
  Desc_Ramp_Asphalt_8x4_C: "Build_Ramp_Asphalt_8x4_C",
  Desc_Ramp_DownCorner_Asphalt_8x1_C: "Build_Ramp_DownCorner_Asphalt_8x1_C",
  Desc_Ramp_DownCorner_Asphalt_8x2_C: "Build_Ramp_DownCorner_Asphalt_8x2_C",
  Desc_Ramp_DownCorner_Asphalt_8x4_C: "Build_Ramp_DownCorner_Asphalt_8x4_C",
  Desc_Ramp_UpCorner_Asphalt_8x1_C: "Build_Ramp_UpCorner_Asphalt_8x1_C",
  Desc_Ramp_UpCorner_Asphalt_8x2_C: "Build_Ramp_UpCorner_Asphalt_8x2_C",
  Desc_Ramp_UpCorner_Asphalt_8x4_C: "Build_Ramp_UpCorner_Asphalt_8x4_C",
  Desc_RampDouble_Asphalt_8x1_C: "Build_RampDouble_Asphalt_8x1_C",
  Desc_RampDouble_Asphalt_8x2_C: "Build_RampDouble_Asphalt_8x2_C",
  Desc_RampDouble_Asphalt_8x4_C: "Build_RampDouble_Asphalt_8x4_C",
  Desc_Stair_Asphalt_8x1_C: "Build_Stair_Asphalt_8x1_C",
  Desc_Stair_Asphalt_8x2_C: "Build_Stair_Asphalt_8x2_C",
  Desc_Stair_Asphalt_8x4_C: "Build_Stair_Asphalt_8x4_C",
  Desc_AlienPowerBuilding_C: "Build_AlienPowerBuilding_C",
  Desc_CentralStorage_C: "Build_CentralStorage_C",
  Desc_GeneratorGeoThermal_C: "Build_GeneratorGeoThermal_C",
  Desc_ConveyorAttachmentSplitterProgrammable_C:
    "Build_ConveyorAttachmentSplitterProgrammable_C",
  Desc_PowerPoleMk3_C: "Build_PowerPoleMk3_C",
  Desc_PriorityPowerSwitch_C: "Build_PriorityPowerSwitch_C",
  Desc_PowerPoleMk2_C: "Build_PowerPoleMk2_C",
  Desc_PowerSwitch_C: "Build_PowerSwitch_C",
  Desc_ConveyorAttachmentSplitterSmart_C:
    "Build_ConveyorAttachmentSplitterSmart_C",
  Desc_RadarTower_C: "Build_RadarTower_C",
  Desc_WreathDecor_C: "Build_WreathDecor_C",
  Desc_SnowCannon_C: "Build_SnowCannon_C",
  Desc_SnowDispenser_C: "Build_SnowDispenser_C",
  Desc_xmassLights_C: "Build_XmassLightsLine_C",
  Desc_TreeGiftProducer_C: "Build_TreeGiftProducer_C",
  Desc_Snowman_C: "Build_Snowman_C",
  Desc_XMassTree_C: "Build_XmassTree_C",
  Desc_CandyCaneDecor_C: "Build_CandyCaneDecor_C",
  Desc_Flat_Frame_01_C: "Build_Flat_Frame_01_C",
  Desc_Foundation_Frame_01_C: "Build_Foundation_Frame_01_C",
  Desc_FoundationGlass_01_C: "Build_FoundationGlass_01_C",
  Desc_Ramp_Frame_01_C: "Build_Ramp_Frame_01_C",
  Desc_Ramp_Frame_Inverted_01_C: "Build_Ramp_Frame_Inverted_01_C",
  Desc_Wall_Frame_01_C: "Build_Wall_Frame_01_C",
  Desc_Railing_01_C: "Build_Railing_01_C",
  Desc_Pillar_Small_Metal_C: "Build_Pillar_Small_Metal_C",
  Desc_PillarBase_Small_C: "Build_PillarBase_Small_C",
  Desc_PillarBase_C: "Build_PillarBase_C",
  Desc_PillarMiddle_C: "Build_PillarMiddle_C",
  Desc_Ladder_C: "Build_Ladder_C",
  Desc_Gate_Automated_8x4_C: "Build_Gate_Automated_8x4_C",
  Desc_HyperTubeWallHole_C: "Build_HyperTubeWallHole_C",
  Desc_PipelineSupportWallHole_C: "Build_PipelineSupportWallHole_C",
  Desc_FoundationPassthrough_Pipe_C: "Build_FoundationPassthrough_Pipe_C",
  Desc_PowerPoleWallDouble_C: "Build_PowerPoleWallDouble_C",
  Desc_PowerPoleWallDoubleMk2_C: "Build_PowerPoleWallDouble_Mk2_C",
  Desc_PowerPoleWallMk2_C: "Build_PowerPoleWall_Mk2_C",
  Desc_PowerPoleWallDoubleMk3_C: "Build_PowerPoleWallDouble_Mk3_C",
  Desc_PowerPoleWallMk3_C: "Build_PowerPoleWall_Mk3_C",
  Desc_StreetLight_C: "Build_StreetLight_C",
  Desc_CeilingLight_C: "Build_CeilingLight_C",
  Desc_FloodlightPole_C: "Build_FloodlightPole_C",
  Desc_FloodlightWall_C: "Build_FloodlightWall_C",
  Desc_Roof_Orange_01_C: "Build_Roof_Orange_01_C",
  Desc_Roof_Orange_02_C: "Build_Roof_Orange_02_C",
  Desc_Roof_Orange_03_C: "Build_Roof_Orange_03_C",
  Desc_Roof_Orange_04_C: "Build_Roof_Orange_04_C",
  Desc_Roof_Orange_InCorner_01_C: "Build_Roof_Orange_InCorner_01_C",
  Desc_Roof_Orange_InCorner_02_C: "Build_Roof_Orange_InCorner_02_C",
  Desc_Roof_Orange_InCorner_03_C: "Build_Roof_Orange_InCorner_03_C",
  Desc_Roof_Orange_OutCorner_01_C: "Build_Roof_Orange_OutCorner_01_C",
  Desc_Roof_Orange_OutCorner_02_C: "Build_Roof_Orange_OutCorner_02_C",
  Desc_Roof_Orange_OutCorner_03_C: "Build_Roof_Orange_OutCorner_03_C",
  Desc_Roof_Window_01_C: "Build_Roof_Window_01_C",
  Desc_Roof_Window_02_C: "Build_Roof_Window_02_C",
  Desc_Roof_Window_03_C: "Build_Roof_Window_03_C",
  Desc_Roof_Window_04_C: "Build_Roof_Window_04_C",
  Desc_Roof_Window_InCorner_01_C: "Build_Roof_Window_InCorner_01_C",
  Desc_Roof_Window_InCorner_02_C: "Build_Roof_Window_InCorner_02_C",
  Desc_Roof_Window_InCorner_03_C: "Build_Roof_Window_InCorner_03_C",
  Desc_Roof_Window_OutCorner_01_C: "Build_Roof_Window_OutCorner_01_C",
  Desc_Roof_Window_OutCorner_02_C: "Build_Roof_Window_OutCorner_02_C",
  Desc_Roof_Window_OutCorner_03_C: "Build_Roof_Window_OutCorner_03_C",
  Desc_Roof_A_01_C: "Build_Roof_A_01_C",
  Desc_Roof_A_02_C: "Build_Roof_A_02_C",
  Desc_Roof_A_03_C: "Build_Roof_A_03_C",
  Desc_Roof_A_04_C: "Build_Roof_A_04_C",
  Desc_Roof_Metal_InCorner_01_C: "Build_Roof_Metal_InCorner_01_C",
  Desc_Roof_Metal_InCorner_02_C: "Build_Roof_Metal_InCorner_02_C",
  Desc_Roof_Metal_InCorner_03_C: "Build_Roof_Metal_InCorner_03_C",
  Desc_Roof_Metal_OutCorner_01_C: "Build_Roof_Metal_OutCorner_01_C",
  Desc_Roof_Metal_OutCorner_02_C: "Build_Roof_Metal_OutCorner_02_C",
  Desc_Roof_Metal_OutCorner_03_C: "Build_Roof_Metal_OutCorner_03_C",
  Desc_Roof_Tar_01_C: "Build_Roof_Tar_01_C",
  Desc_Roof_Tar_02_C: "Build_Roof_Tar_02_C",
  Desc_Roof_Tar_03_C: "Build_Roof_Tar_03_C",
  Desc_Roof_Tar_04_C: "Build_Roof_Tar_04_C",
  Desc_Roof_Tar_InCorner_01_C: "Build_Roof_Tar_InCorner_01_C",
  Desc_Roof_Tar_InCorner_02_C: "Build_Roof_Tar_InCorner_02_C",
  Desc_Roof_Tar_InCorner_03_C: "Build_Roof_Tar_InCorner_03_C",
  Desc_Roof_Tar_OutCorner_01_C: "Build_Roof_Tar_OutCorner_01_C",
  Desc_Roof_Tar_OutCorner_02_C: "Build_Roof_Tar_OutCorner_02_C",
  Desc_Roof_Tar_OutCorner_03_C: "Build_Roof_Tar_OutCorner_03_C",
  Desc_PipelineMK2_NoIndicator_C: "Build_PipelineMK2_NoIndicator_C",
  Desc_Pipeline_NoIndicator_C: "Build_Pipeline_NoIndicator_C",
  Desc_StorageMedkit_C: "Build_StorageMedkit_C",
  Desc_LightsControlPanel_C: "Build_LightsControlPanel_C",
  Desc_StandaloneWidgetSign_Small_C: "Build_StandaloneWidgetSign_Small_C",
  Desc_StandaloneWidgetSign_SmallVeryWide_C:
    "Build_StandaloneWidgetSign_SmallVeryWide_C",
  Desc_StandaloneWidgetSign_SmallWide_C:
    "Build_StandaloneWidgetSign_SmallWide_C",
  Desc_StandaloneWidgetSign_Square_Tiny_C:
    "Build_StandaloneWidgetSign_Square_Tiny_C",
  Desc_FoundationPassthrough_Hypertube_C:
    "Build_FoundationPassthrough_Hypertube_C",
  Desc_StorageHazard_C: "Build_StorageHazard_C",
  Desc_Wall_Window_8x4_05_C: "Build_Wall_Window_8x4_05_C",
  Desc_Wall_Window_8x4_06_C: "Build_Wall_Window_8x4_06_C",
  Desc_Wall_Window_8x4_07_C: "Build_Wall_Window_8x4_07_C",
  Desc_Wall_Window_Thin_8x4_01_C: "Build_Wall_Window_Thin_8x4_01_C",
  Desc_Wall_Window_Thin_8x4_02_C: "Build_Wall_Window_Thin_8x4_02_C",
  Desc_Pillar_Small_Frame_C: "Build_Pillar_Small_Frame_C",
  Desc_PillarMiddle_Frame_C: "Build_PillarMiddle_Frame_C",
  Desc_ChainLinkFence_C: "Build_ChainLinkFence_C",
  Desc_TarpFence_C: "Build_TarpFence_C",
  Desc_Barrier_Low_01_C: "Build_Barrier_Low_01_C",
  Desc_Barrier_Tall_01_C: "Build_Barrier_Tall_01_C",
  Desc_Concrete_Barrier_01_C: "Build_Concrete_Barrier_01_C",
  Desc_StandaloneWidgetSign_Medium_C: "Build_StandaloneWidgetSign_Medium_C",
  Desc_StandaloneWidgetSign_Portrait_C: "Build_StandaloneWidgetSign_Portrait_C",
  Desc_StandaloneWidgetSign_Square_C: "Build_StandaloneWidgetSign_Square_C",
  Desc_StandaloneWidgetSign_Square_Small_C:
    "Build_StandaloneWidgetSign_Square_Small_C",
  Desc_FoundationPassthrough_Lift_C: "Build_FoundationPassthrough_Lift_C",
  Desc_Pillar_Small_Concrete_C: "Build_Pillar_Small_Concrete_C",
  Desc_PillarMiddle_Concrete_C: "Build_PillarMiddle_Concrete_C",
  Desc_CatwalkCross_C: "Build_CatwalkCross_C",
  Desc_CatwalkRamp_C: "Build_CatwalkRamp_C",
  Desc_CatwalkStairs_C: "Build_CatwalkStairs_C",
  Desc_CatwalkStraight_C: "Build_CatwalkStraight_C",
  Desc_CatwalkT_C: "Build_CatwalkT_C",
  Desc_CatwalkTurn_C: "Build_CatwalkCorner_C",
  Desc_StandaloneWidgetSign_Huge_C: "Build_StandaloneWidgetSign_Huge_C",
  Desc_StandaloneWidgetSign_Large_C: "Build_StandaloneWidgetSign_Large_C",
  Desc_Beam_Connector_C: "Build_Beam_Connector_C",
  Desc_Beam_Connector_Double_C: "Build_Beam_Connector_Double_C",
  Desc_Beam_Support_C: "Build_Beam_Support_C",
  Desc_GeneratorBiomass_Automated_C: "Build_GeneratorBiomass_Automated_C",
  Desc_SpaceElevator_C: "Build_SpaceElevator_C",
  Desc_MinerMk1_C: "Build_MinerMk1_C",
  Desc_StorageContainerMk1_C: "Build_StorageContainerMk1_C",
  Desc_ConstructorMk1_C: "Build_ConstructorMk1_C",
  Desc_SmelterMk1_C: "Build_SmelterMk1_C",
  Desc_Workshop_C: "Build_Workshop_C",
  Desc_ConveyorPole_C: "Build_ConveyorPole_C",
  Desc_PipelineSupport_C: "Build_PipelineSupport_C",
  Desc_PipeSupportStackable_C: "Build_PipeSupportStackable_C",
  Desc_HyperPoleStackable_C: "Build_HyperPoleStackable_C",
  Desc_PipeHyperSupport_C: "Build_PipeHyperSupport_C",
  Desc_ConveyorPoleStackable_C: "Build_ConveyorPoleStackable_C",
  // cspell:enable
};
