name: Lint Markdown

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint_markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm run lint:md-full
