name: Lint CSS

on:
  workflow_dispatch:
  workflow_call:

jobs:
  lint_css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm run generate
      - run: pnpm run lint:css-full
