name: Lint Knip (Development)

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  lint_knip_dev:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: pnpm run lint:knip:development
